### ISSUE TITLE
Small issue converting

### ISSUE THREAD

**Issue by ghost** [binxio/serverless-cfnflip#3] opened 2019-08-19 09:38 UTC
Tried to convert this: https://s3.amazonaws.com/aws-configservice-us-east-1/cloudformation-templates-for-managed-rules/IAM_USER_GROUP_MEMBERSHIP_CHECK.template

The condition did not come out right. 

It should be:

```yaml
Conditions:
  groupNames: !Not
    - !Equals
      - ''
      - !Ref groupNames
``` 

But it comes out as 
```yaml
Conditions:
  groupNames: !Not
    - !Equals
      - ''
```

**Comment by PatMyron** [comment] 2019-12-17 04:09
Issues involving the generated output itself are probably better suited for https://github.com/awslabs/aws-cfn-template-flip

Unable to reproduce this via the website or the CLI, so I think this is fixed in both now anyway

**Closed as completed** 2020-04-03 00:30 UTC
